# Generated by Django 4.1.3 on 2022-11-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenexchangemodel',
            name='access_token',
            field=models.CharField(max_length=300),
        ),
    ]
